sonar.organization=Yurii-Marchak
sonar.projectKey=yurii-marchak
sonar.projectName=SubOptima-Subscription-Optimizer

# Шляхи до вихідного коду та тестів
sonar.sources=src
sonar.tests=tests

# Мовні налаштування та кодування
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

# Шляхи до згенерованих звітів тестування та покриття (для зв'язку з pytest)
sonar.junit.reportPaths=junit.xml
sonar.python.coverage.reportPaths=coverage.xml

# Виключення з аналізу (щоб тести не рахувалися як бізнес-код)
sonar.exclusions=tests/**, **/migrations/**